export default {
  TRENDING_REPO_INIT: 'TRENDING_REPO/TRENDING_REPO_INIT',
  TRENDING_REPO_ADD: 'TRENDING_REPO/TRENDING_REPO_ADD',
  TRENDING_REPO_CLEAN: 'TRENDING_REPO/TRENDING_REPO_CLEAN',
  TRENDING_REPO_NO_MORE: 'TRENDING_REPO/TRENDING_REPO_NO_MORE'
}
