export default {
  USER_REPO_INIT: 'USERREPO/USER_REPO_INIT',
  USER_REPO_ADD: 'USERREPO/USER_REPO_ADD',
  USER_REPO_CLEAN: 'USERREPO/USER_REPO_CLEAN',
  USER_REPO_NO_MORE: 'USERREPO/USER_REPO_NO_MORE'
}
