export default {
  LOADING_TRUE: 'LOADING/LOADING_TRUE',
  LOADING_FALSE: 'LOADING/LOADING_FALSE',
  SHOW_MODAL: 'MODAL/SHOW_MODAL',
  CLOSE_MODAL: 'MODAL/CLOSE_MODAL',
  SHOW_SNACKBAR: 'SNACKBAR/SHOW_SNACKBAR',
  CLOSE_SNACKBAR: 'SNACKBAR/CLOSE_SNACKBAR'
}
